# Generated by Django 5.1.4 on 2025-01-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=123131313, max_length=100),
            preserve_default=False,
        ),
    ]


