# Generated by Django 5.1.4 on 2025-01-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_personinfo_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
    ]
