# Generated by Django 5.1.4 on 2025-01-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_personinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
